### ISSUE TITLE
Override default values for boolean flags

### ISSUE THREAD

**Issue by amotl** [asottile/covdefaults#51]
Dear Anthony,

while working on https://github.com/daq-tools/wireviz-web/pull/1, we believe we just discovered a minor flaw when trying to override the default values for the boolean flags `show_missing` and `skip_covered`. Is it possible that I am not able to toggle 
`skip_covered = false`, where its default is `True` [1]?

```toml
[tool.coverage.run]
plugins = ["covdefaults"]

[tool.coverage.report]
fail_under = 90
show_missing = true
skip_covered = false
```

With kind regards,
Andreas.

[1] https://github.com/asottile/covdefaults/blob/v2.0.0/covdefaults.py#L30-L35
